In [ ]:
import math
import string

import random
import time

import numpy as np

### Exercice 1

In [22]:
def nextpower(n):
    
    nextPowerOf2 = 1
    
    i = 0
    while (nextPowerOf2 < n):
        nextPowerOf2 = math.pow(2, i)
        i = i + 1

    return int(nextPowerOf2)

print(nextpower(0))
print(nextpower(16))

1
16


### Exercice 2

In [16]:
alphabet = string.ascii_letters[0:26]

print(alphabet[2:26:3])
print(alphabet[21:26:2])
print(alphabet[-5::2])

cfilorux
vxz
vxz


### Exercice 3

In [23]:
print("{:.9f}".format(math.pi))

3.141592654


### Exercice 4

In [33]:
def wordCount(s):
    
    dico = {}
    for char in s:
        if char in dico:
            dico[char] += 1
        else:
            dico[char] = 1
    
    return dico

s = "HelLo WorLd!!"

t = time.time()

print(wordCount(s))
print("running time = {}".format(time.time() - t))

{'H': 1, 'e': 1, 'l': 1, 'L': 2, 'o': 2, ' ': 1, 'W': 1, 'r': 1, 'd': 1, '!': 2}
running time = 0.0003216266632080078


### Exercice 5

In [65]:
def cesar_keygen(seed=None):
    
    random.seed(seed)
 
    #alphabet = list(string.ascii_letters[0:26])    
    #key_list = list(string.ascii_letters[0:26])
 
    alphabet = list(string.printable)    
    key_list = list(string.printable)

    random.shuffle(key_list)

    encoder = {}
    decoder = {}

    for idx, char in enumerate(alphabet):
        key = key_list[idx]
        encoder[char] = key
        decoder[key] = char

    return (encoder, decoder)

def cesar_encode(encoder, string):
    
    list_in = list(string)
    list_out = []
    
    for char in list_in:
        list_out.append(encoder[char])
    
    return "".join(list_out)

def cesar_decode(decoder, string):
    list_in = list(string)
    list_out = []
    
    for char in list_in:
        list_out.append(decoder[char])
    
    return "".join(list_out)

encoder, decoder = cesar_keygen(seed=12)

s1 = "toto"

s2 = cesar_encode(encoder, s1)

print(s2)

s3 = cesar_decode(decoder, s2)

print(s3)
#print(encoder)
#print(decoder)
    

"@"@
toto


### Exercice 6

In [93]:
def product_1(n):
    """with loop"""
    result = 1.0
    for k in range(1, n + 1):
        k2 = float(k * k)
        tmp = 4. * k2 / (4. * k2 - 1.)
        result *= tmp
        
    return 2.0 * result

def product_2(n):
    """with numpy"""
    k = np.arange(1, n + 1, dtype=np.float)
    k2 = np.square(k)
    a = 4. * k2 / (4. * k2 - 1.)
    
    return 2.0 * np.prod(a)
    
n = 1000000

t1 = time.time()

v1 = product_1(n)
t2 = time.time()

print("n = {} => v = {} //// t = {:.6f}".format(n, v1, t2 - t1))

v2 = product_2(n)
t3 = time.time()

print("n = {} => v = {} //// t = {:.6f}".format(n, v2, t3 - t2))
            

n = 1000000 => v = 3.141591868192149 //// t = 0.476625
n = 1000000 => v = 3.141591868192149 //// t = 0.029289


### Exercice 7

In [112]:
def quicksort(ll):
    """ a sorting algorithm with a pivot value"""
    
    print("Enter => " + str(ll))
    if len(ll) <= 1:
        return ll
    else:
        # pivot = last element of the list ll.
        pivot = ll.pop()
        less = []
        greater = []

        for x in ll:
            if x <= pivot:
                less.append(x)
            else:
                greater.append(x)

        res = []
        if (len(less) > 0):
            res.extend(quicksort(less))
            
        res.append(pivot)
        
        if (len(greater) > 0):
            res.extend(quicksort(greater))

        return res


ll = [-2, 3, 5, 1, 3]
                                      
print(quicksort(ll))


Enter => [-2, 3, 5, 1, 3]
Enter => [-2, 3, 1]
Enter => [-2]
Enter => [3]
Enter => [5]
[-2, 1, 3, 3, 5]


### Exercice 8

In [119]:
np.random.seed(4)

mat = np.random.uniform(-1.0, 1.0, (5, 6))


print(mat)

print(mat[:, :2:2])

[[ 0.93405968  0.0944645   0.94536872  0.42963199  0.39545765 -0.56782101]
 [ 0.95254891 -0.98753949 -0.49403528 -0.13041694  0.55876584 -0.60462985]
 [ 0.72598647  0.96680135 -0.67231552  0.19466789 -0.9820278  -0.22685743]
 [-0.91167988  0.91330594 -0.12770671  0.89795461  0.57261197  0.7325786 ]
 [-0.65366916 -0.85010283  0.20148544 -0.66405563  0.46676034 -0.18311228]]
[[ 0.93405968  0.0944645   0.94536872  0.42963199  0.39545765 -0.56782101]
 [ 0.95254891 -0.98753949 -0.49403528 -0.13041694  0.55876584 -0.60462985]]
