# Introduction: Python, Numpy, Pandas, *et al*.

In [1]:
import math
import string

import random
import time

import numpy as np

### Exercice 1

In [2]:
def nextpower(n):
    
    nextPowerOf2 = 1
    
    i = 0
    while (nextPowerOf2 < n):
        nextPowerOf2 = math.pow(2, i)
        i = i + 1

    return int(nextPowerOf2)

print(nextpower(0))
print(nextpower(16))

1
16


### Exercice 2

In [3]:
alphabet = string.ascii_letters[0:26]

print(alphabet[2:26:3])
print(alphabet[21:26:2])
print(alphabet[-5::2])

cfilorux
vxz
vxz


### Exercice 3

In [4]:
print("{:.9f}".format(math.pi))

3.141592654


### Exercice 4

In [5]:
def wordCount(s):
    
    dico = {}
    for char in s:
        if char in dico:
            dico[char] += 1
        else:
            dico[char] = 1
    
    return dico

s = "HelLo WorLd!!"

t = time.time()

print(wordCount(s))
print("running time = {}".format(time.time() - t))

{'H': 1, 'e': 1, 'l': 1, 'L': 2, 'o': 2, ' ': 1, 'W': 1, 'r': 1, 'd': 1, '!': 2}
running time = 0.0


### Exercice 5

In [6]:
def cesar_keygen(seed=None):
    
    random.seed(seed)
 
    #alphabet = list(string.ascii_letters[0:26])    
    #key_list = list(string.ascii_letters[0:26])
 
    alphabet = list(string.printable)    
    key_list = list(string.printable)

    random.shuffle(key_list)

    encoder = {}
    decoder = {}

    for idx, char in enumerate(alphabet):
        key = key_list[idx]
        encoder[char] = key
        decoder[key] = char

    return (encoder, decoder)

def cesar_encode(encoder, string):
    
    list_in = list(string)
    list_out = []
    
    for char in list_in:
        list_out.append(encoder[char])
    
    return "".join(list_out)

def cesar_decode(decoder, string):
    list_in = list(string)
    list_out = []
    
    for char in list_in:
        list_out.append(decoder[char])
    
    return "".join(list_out)

encoder, decoder = cesar_keygen(seed=12)

s1 = "toto"

s2 = cesar_encode(encoder, s1)

print(s2)

s3 = cesar_decode(decoder, s2)

print(s3)
#print(encoder)
#print(decoder)
    

"@"@
toto


### Exercice 6

In [7]:
def product_1(n):
    """with loop"""
    result = 1.0
    for k in range(1, n + 1):
        k2 = float(k * k)
        tmp = 4. * k2 / (4. * k2 - 1.)
        result *= tmp
        
    return 2.0 * result

def product_2(n):
    """with numpy"""
    k = np.arange(1, n + 1, dtype=np.float)
    k2 = np.square(k)
    a = 4. * k2 / (4. * k2 - 1.)
    
    return 2.0 * np.prod(a)
    
n = 1000000

t1 = time.time()

v1 = product_1(n)
t2 = time.time()

print("n = {} => v = {} //// t = {:.6f}".format(n, v1, t2 - t1))

v2 = product_2(n)
t3 = time.time()

print("n = {} => v = {} //// t = {:.6f}".format(n, v2, t3 - t2))
            

n = 1000000 => v = 3.141591868192149 //// t = 0.682303
n = 1000000 => v = 3.141591868192149 //// t = 0.059943


### Exercice 7

In [8]:
import copy

def quicksort(listInt):
    """ a sorting algorithm with a pivot value"""
    
    ll = copy.deepcopy(listInt)
    if len(ll) <= 1:
        return ll
    else:
        # pivot = last element of the list ll.
        pivot = ll.pop()
        less = []
        greater = []

        for x in ll:
            if x <= pivot:
                less.append(x)
            else:
                greater.append(x)

        res = []
        if (len(less) > 0):
            res.extend(quicksort(less))
            
        res.append(pivot)
        
        if (len(greater) > 0):
            res.extend(quicksort(greater))

        return res

l1 = [-2, 3, 5, 1, 3]
l2 = quicksort(l1)

print("{} => {}".format(l1, l2))

[-2, 3, 5, 1, 3] => [-2, 1, 3, 3, 5]


### Exercice 8

$\mathbf{M} \in \mathbb{R}^{5 \times 6}$

In [24]:
np.random.seed(4)

mat = np.random.uniform(-1.0, 1.0, (5, 6))

print("A = {}".format(mat))

mat[:, ::2] -= 2.0 * mat[:, 1::2]

print("A = {}".format(mat))

# Remplace les valeurs négatives par 0.
mat[mat < 0] = 0.0

print("A = {}".format(mat))


A = [[ 0.93405968  0.0944645   0.94536872  0.42963199  0.39545765 -0.56782101]
 [ 0.95254891 -0.98753949 -0.49403528 -0.13041694  0.55876584 -0.60462985]
 [ 0.72598647  0.96680135 -0.67231552  0.19466789 -0.9820278  -0.22685743]
 [-0.91167988  0.91330594 -0.12770671  0.89795461  0.57261197  0.7325786 ]
 [-0.65366916 -0.85010283  0.20148544 -0.66405563  0.46676034 -0.18311228]]
A = [[ 0.74513068  0.0944645   0.08610475  0.42963199  1.53109967 -0.56782101]
 [ 2.92762789 -0.98753949 -0.2332014  -0.13041694  1.76802555 -0.60462985]
 [-1.20761624  0.96680135 -1.06165129  0.19466789 -0.52831294 -0.22685743]
 [-2.73829175  0.91330594 -1.92361593  0.89795461 -0.89254522  0.7325786 ]
 [ 1.04653649 -0.85010283  1.52959671 -0.66405563  0.83298489 -0.18311228]]
A = [[0.74513068 0.0944645  0.08610475 0.42963199 1.53109967 0.        ]
 [2.92762789 0.         0.         0.         1.76802555 0.        ]
 [0.         0.96680135 0.         0.19466789 0.         0.        ]
 [0.         0.91330594 0.   

### Exercice 9

$\mathbf{M} \in \mathbb{R}^{5 \times 20}$

In [27]:
np.random.seed(4)

M = np.random.uniform(-1.0, 1.0, (5, 6))

G = np.dot(M.T, M)

print(G)

a = (G == G.T)

print(a)

[[ 3.56531684 -0.42751613 -0.09093111  0.03382519 -0.63845171 -1.81919596]
 [-0.42751613  3.47566519 -0.36073106  1.74220487 -1.33769681  1.1488635 ]
 [-0.09093111 -0.36073106  1.64670641  0.0912406   0.77895481 -0.21602163]
 [ 0.03382519  1.74220487  0.0912406   1.48678018  0.11008418  0.57015712]
 [-0.63845171 -1.33769681  0.77895481  0.11008418  1.97873431 -0.00560164]
 [-1.81919596  1.1488635  -0.21602163  0.57015712 -0.00560164  1.30966376]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


# Introduction à Pandas, Matplotlib, etc.

### Exercice 10

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("household_power_consumption_short.csv", sep=";",
                   low_memory=False)



df.head(10)

Date      Time Global_active_power Global_reactive_power  Voltage  \
0  16/12/2006  17:24:00               4.216                 0.418  234.840   
1  16/12/2006  17:25:00               5.360                 0.436  233.630   
2  16/12/2006  17:26:00               5.374                 0.498  233.290   
3  16/12/2006  17:27:00               5.388                 0.502  233.740   
4  16/12/2006  17:28:00               3.666                 0.528  235.680   
5  16/12/2006  17:29:00               3.520                 0.522  235.020   
6  16/12/2006  17:30:00               3.702                 0.520  235.090   
7  16/12/2006  17:31:00               3.700                 0.520  235.220   
8  16/12/2006  17:32:00               3.668                 0.510  233.990   
9  16/12/2006  17:33:00               3.662                 0.510  233.860   

  Global_intensity Sub_metering_1 Sub_metering_2  Sub_metering_3  
0           18.400          0.000          1.000            17.0  
1           23.000          0.000          1.000            16.0  
2           23.000          0.000          2.000            17.0  
3           23.000          0.000          1.000            17.0  
4           15.800          0.000          1.000            17.0  
5           15.000          0.000          2.000            17.0  
6           15.800          0.000          1.000            17.0  
7           15.800          0.000          1.000            17.0  
8           15.800          0.000          1.000            17.0  
9           15.800          0.000          2.000            16.0

In [9]:
df.describe(include="all")

Date      Time Global_active_power Global_reactive_power Voltage  \
count      199998    199998              199998                199998  199998   
unique        140      1440                3610                   391    2282   
top     29/4/2007  18:13:00                   ?                 0.000       ?   
freq         1440       139                3732                 54221    3732   
mean          NaN       NaN                 NaN                   NaN     NaN   
std           NaN       NaN                 NaN                   NaN     NaN   
min           NaN       NaN                 NaN                   NaN     NaN   
25%           NaN       NaN                 NaN                   NaN     NaN   
50%           NaN       NaN                 NaN                   NaN     NaN   
75%           NaN       NaN                 NaN                   NaN     NaN   
max           NaN       NaN                 NaN                   NaN     NaN   

       Global_intensity Sub_metering_1 Sub_metering_2  Sub_metering_3  
count            199998         199998         199998   196266.000000  
unique              205             72             80             NaN  
top               1.400          0.000          0.000             NaN  
freq              18440         180327         138358             NaN  
mean                NaN            NaN            NaN        6.443801  
std                 NaN            NaN            NaN        8.428525  
min                 NaN            NaN            NaN        0.000000  
25%                 NaN            NaN            NaN        0.000000  
50%                 NaN            NaN            NaN        0.000000  
75%                 NaN            NaN            NaN       17.000000  
max                 NaN            NaN            NaN       20.000000

### Exercice 11

In [12]:
print(pd.mean(df["Sub_metering_1"]))

df.dropna(inplace=True)

df.describe(include="all")

AttributeError: module 'pandas' has no attribute 'mean'